function presets = ct_window_presets()
%CT_WINDOW_PRESETS  Common CT window center / width (HU).
    presets = struct( ...
        'name', {'Lung', 'Soft tissue', 'Bone', 'Abdomen', 'Brain'}, ...
        'center', {-600, 40, 400, 40, 40}, ...
        'width', {1500, 400, 1800, 350, 80});
end
