<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\CT3D.Core\CT3D.Core.csproj" />
    <ProjectReference Include="..\CT3D.Dicom\CT3D.Dicom.csproj" />
    <ProjectReference Include="..\CT3D.Rendering\CT3D.Rendering.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

</Project>
